-- Create a complete test and implementation module for a data type Vector
-- Vector can be constructed with three positive coordinates (x, y, z).
-- Vectors can be added, subtracted and multiplied. Choose whatever vector
-- product you feel like.
-- Make sure Vector can be used in existing calculations (more precisely, use the Num-type class).
-- Have fun with stack, cabal, hspec and maybe quickcheck. Examples can be found in the first four exercises.
